# Tensaku — Modern Screenshot Annotation (Omarchy app).
#
# A Rust/GTK4/libadwaita screenshot annotation tool used by the Omarchy
# Quattro desktop. Fork of Satty, licensed MPL-2.0. Vendored here because
# nixpkgs does not (yet) ship a `tensaku` package; this derivation pins a
# tagged upstream release and builds the cargo workspace.
#
# Build deps follow the upstream flake.nix devshell (pkg-config, libGL,
# libepoxy, gtk4, wrapGAppsHook4, libadwaita, fontconfig) plus
# gtk4-layer-shell, which the `gtk4-layer-shell` crate (a scroll-capture
# and fullscreen-overlay dependency) links against via pkg-config.
{
  lib,
  stdenv,
  rustPlatform,
  fetchFromGitHub,
  pkg-config,
  wrapGAppsHook4,
  gtk4,
  libadwaita,
  libepoxy,
  libGL,
  fontconfig,
  gtk4-layer-shell,
}:

rustPlatform.buildRustPackage (finalAttrs: {
  pname = "tensaku";
  version = "0.26.6";

  src = fetchFromGitHub {
    owner = "jondkinney";
    repo = "tensaku";
    # Annotated tag v0.26.6 -> commit.
    rev = "a7f578e4bc26202d2975210327d9f95deffd7957";
    hash = "sha256-br4/PqdrPwB86Fgwv+ujAdRFFqJzUpM//AzR7NC5QTI=";
  };

  cargoHash = "sha256-oh5WTHfgeecZ4IHWX2/zIWpB8KVxPW5+dyjcGMD82dk=";

  # build.rs generates shell completions + a manpage into OUT_DIR (the
  # `ci-release` cargo feature would write them next to sources for the
  # release tarball; we deliberately do not enable it so the artifacts stay
  # in OUT_DIR and don't pollute the source tree).
  nativeBuildInputs = [
    pkg-config
    wrapGAppsHook4
  ];

  buildInputs = [
    gtk4
    libadwaita
    libepoxy
    libGL
    fontconfig
    # Links the system C lib needed by the `gtk4-layer-shell` crate used for
    # the scroll-capture overlay and layer-shell fullscreen mode.
    gtk4-layer-shell
  ];

  # Install the .desktop entry + SVG app icon (named dev.tensaku.Tensaku to
  # match Icon= in the desktop file and the StartupWMClass). The cargo
  # build already installs the `tensaku` binary; this just wires desktop
  # integration. Completions/manpage generated by build.rs live in a
  # cargo-internal OUT_DIR and are intentionally not chased here.
  postInstall = ''
    install -Dm644 dev.tensaku.Tensaku.desktop \
      $out/share/applications/dev.tensaku.Tensaku.desktop
    install -Dm644 assets/tensaku.svg \
      $out/share/icons/hicolor/scalable/apps/dev.tensaku.Tensaku.svg

    # tensaku-edit: the wrapper upstream's Arch package ships at
    # /usr/bin/tensaku-edit (verified on the reference box, tensaku 0.26.6-1).
    # Omarchy's screenshot scripts (omarchy-capture-screenshot,
    # omarchy-clipboard-open, imv Ctrl+e) hand a single bare image path to
    # $OMARCHY_SCREENSHOT_EDITOR (default: tensaku-edit); tensaku has no
    # positional filename argument, so the wrapper supplies the flags —
    # matching what Omarchy's built-in editor branch passes. Absolute store
    # path for tensaku (upstream uses a bare name relying on PATH); wl-copy
    # stays bare (session PATH — wl-clipboard is in runtimeDeps).
    cat > $out/bin/tensaku-edit <<'TENSAKU_EDIT'
    #!/bin/sh
    # Opens Tensaku to annotate a screenshot (upstream Omarchy wrapper parity).
    exec TENSAKU_BIN \
      --filename "$1" \
      --output-filename "$1" \
      --actions-on-enter save-to-clipboard \
      --save-after-copy \
      --copy-command wl-copy
    TENSAKU_EDIT
    substituteInPlace $out/bin/tensaku-edit --replace-fail TENSAKU_BIN "$out/bin/tensaku"
    chmod +x $out/bin/tensaku-edit
  '';

  meta = {
    description = "Modern screenshot annotation tool (Omarchy; fork of Satty)";
    homepage = "https://github.com/jondkinney/tensaku";
    license = lib.licenses.mpl20;
    platforms = lib.platforms.linux;
    mainProgram = "tensaku";
  };
})
