# Tensaku — Modern Screenshot Annotation (Omarchy app).
#
# A Rust/GTK4/libadwaita screenshot annotation tool used by the Omarchy
# Quattro desktop. Fork of Satty, licensed MPL-2.0. Vendored here because
# nixpkgs does not (yet) ship a `tensaku` package; this derivation pins a
# tagged upstream release and builds the cargo workspace.
#
# Build deps follow the upstream flake.nix devshell (pkg-config, libGL,
# libepoxy, gtk4, wrapGAppsHook4, libadwaita, fontconfig) plus
# gtk4-layer-shell, which the `gtk4-layer-shell` crate (a scroll-capture
# and fullscreen-overlay dependency) links against via pkg-config.
{
  lib,
  stdenv,
  rustPlatform,
  fetchFromGitHub,
  pkg-config,
  wrapGAppsHook4,
  gtk4,
  libadwaita,
  libepoxy,
  libGL,
  fontconfig,
  gtk4-layer-shell,
  # 0.29 gained input handling (keycode/xkeysym/evdev crates) and links
  # xkbcommon directly.
  libxkbcommon,
}:

rustPlatform.buildRustPackage (finalAttrs: {
  pname = "tensaku";
  version = "0.29.0";

  src = fetchFromGitHub {
    owner = "jondkinney";
    repo = "tensaku";
    # Annotated tag v0.29.0 -> commit.
    rev = "4bcd8339bc22e74bd81c9f3efdfdfcbcf461db70";
    hash = "sha256-IAjvMaN0R+dPtdOR26uLYRT+yjpIz/ZA3V4pKa6nue4=";
  };

  cargoHash = "sha256-q+jS+NX/AKWwaidEQrJMF2hMW+UCb1XJ9zA9Tc5iH5A=";

  # build.rs generates shell completions + a manpage into OUT_DIR (the
  # `ci-release` cargo feature would write them next to sources for the
  # release tarball; we deliberately do not enable it so the artifacts stay
  # in OUT_DIR and don't pollute the source tree).
  nativeBuildInputs = [
    pkg-config
    wrapGAppsHook4
  ];

  buildInputs = [
    gtk4
    libadwaita
    libepoxy
    libGL
    fontconfig
    # Links the system C lib needed by the `gtk4-layer-shell` crate used for
    # the scroll-capture overlay and layer-shell fullscreen mode.
    gtk4-layer-shell
    # 0.29's input handling links xkbcommon directly (the `xkbcommon` crate).
    libxkbcommon
  ];

  # Install the .desktop entry + SVG app icon (named dev.tensaku.Tensaku to
  # match Icon= in the desktop file and the StartupWMClass). The cargo
  # build already installs the `tensaku` binary; this just wires desktop
  # integration. Completions/manpage generated by build.rs live in a
  # cargo-internal OUT_DIR and are intentionally not chased here.
  postInstall = ''
    install -Dm644 dev.tensaku.Tensaku.desktop \
      $out/share/applications/dev.tensaku.Tensaku.desktop
    install -Dm644 assets/tensaku.svg \
      $out/share/icons/hicolor/scalable/apps/dev.tensaku.Tensaku.svg

    # tensaku-edit: the wrapper upstream's Arch package ships at
    # /usr/bin/tensaku-edit (verified on the reference box, tensaku 0.26.6-1).
    # Omarchy's screenshot scripts (omarchy-capture-screenshot,
    # omarchy-clipboard-open, imv Ctrl+e) hand a single bare image path to
    # $OMARCHY_SCREENSHOT_EDITOR (default: tensaku-edit); tensaku has no
    # positional filename argument, so the wrapper supplies the flags —
    # matching what Omarchy's built-in editor branch passes. Absolute store
    # path for tensaku (upstream uses a bare name relying on PATH); wl-copy
    # stays bare (session PATH — wl-clipboard is in runtimeDeps).
    cat > $out/bin/tensaku-edit <<'TENSAKU_EDIT'
    #!/bin/sh
    # Opens Tensaku to annotate a screenshot (upstream Omarchy wrapper parity).
    exec TENSAKU_BIN \
      --filename "$1" \
      --output-filename "$1" \
      --actions-on-enter save-to-clipboard \
      --save-after-copy \
      --copy-command wl-copy
    TENSAKU_EDIT
    substituteInPlace $out/bin/tensaku-edit --replace-fail TENSAKU_BIN "$out/bin/tensaku"
    chmod +x $out/bin/tensaku-edit
  '';

  # 0.29.0: upstream's every-format encoder test asserts exact TIFF bytes
  # and fails in the Nix sandbox (265/266 pass; the RGBA bytes come back
  # unencoded). The encoder is still exercised end-to-end by the
  # checks.omarchy-ux capture/edit flow, so skip only this test.
  checkFlags = [
    "--skip=image_export::tests::every_available_encoder_writes_the_selected_format_from_rgb_and_rgba"
  ];

  meta = {
    description = "Modern screenshot annotation tool (Omarchy; fork of Satty)";
    homepage = "https://github.com/jondkinney/tensaku";
    license = lib.licenses.mpl20;
    platforms = lib.platforms.linux;
    mainProgram = "tensaku";
  };
})
